package com.agri.dashboard.repository;

import com.agri.dashboard.model.CropYield;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * Spring Data JPA repository for CropYield.
 * All standard CRUD methods are auto-generated by Spring Data.
 */
@Repository
public interface CropYieldRepository extends JpaRepository<CropYield, Long> {

    List<CropYield> findByCropNameIgnoreCase(String cropName);

    List<CropYield> findByYear(Integer year);

    List<CropYield> findByRegionIgnoreCaseOrderByYearAsc(String region);

    @Query("SELECT c FROM CropYield c WHERE LOWER(c.cropName) = LOWER(:cropName) AND c.year = :year")
    List<CropYield> findByCropNameAndYear(
            @Param("cropName") String cropName,
            @Param("year") Integer year);
}
